name: cf-mgmt
version: 1.0.6
targets:
- platform: linux    
  tasks:
  - download:
      url: https://github.com/pivotalservices/cf-mgmt/releases/download/v((version))/cf-mgmt-linux
      out: cf-mgmt-((version))-linux
- platform: windows    
  tasks:
  - download:
      url: https://github.com/pivotalservices/cf-mgmt/releases/download/v((version))/cf-mgmt.exe
      out: cf-mgmt-((version))-windows.exe    
- platform: darwin    
  tasks:
  - download:
      url: https://github.com/pivotalservices/cf-mgmt/releases/download/v((version))/cf-mgmt-osx
      out: cf-mgmt-((version))-darwin    
