name: om
version: 0.42.0
targets:
- platform: linux
  tasks:
  - download:
      url: https://github.com/pivotal-cf/om/releases/download/((version))/om-linux
      out: om-((version))-linux
- platform: darwin
  tasks:
  - download:
      url: https://github.com/pivotal-cf/om/releases/download/((version))/om-darwin
      out: om-((version))-darwin
- platform: windows
  tasks:
  - download:
      url: https://github.com/pivotal-cf/om/releases/download/((version))/om-windows.exe
      out: om-((version))-windows.exe
