name: yaml_patch
version: 0.0.11
targets:
- platform: windows
  tasks:
  - download:
      url: https://github.com/pivotal-cf/yaml-patch/releases/download/v0.0.11/yaml_patch.exe
      out: yaml_patch_((version))_windows.exe
- platform: linux
  tasks:
  - download:
      url: https://github.com/pivotal-cf/yaml-patch/releases/download/v0.0.11/yaml_patch_linux
      out: yaml_patch_((version))_linux
- platform: darwin
  tasks:
  - download:
      url: https://github.com/pivotal-cf/yaml-patch/releases/download/v0.0.11/yaml_patch_darwin
      out: yaml_patch_((version))_darwin
