name: bbr
version: 1.2.8
targets:
- platform: linux 
  tasks:
  - download:
      url: https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/download/v((version))/bbr-((version)).tar
      out: bbr-((version))-linux.tar
  - extract:
      archive: bbr-((version))-linux.tar
  - move:
      source: bbr
      destination: bbr-((version))-linux
- platform: darwin
  tasks:
  - download:
      url: https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/download/v((version))/bbr-((version)).tar
      out: bbr-((version))-linux.tar
  - extract:
      archive: bbr-((version))-darwin.tar
  - move:
      source: bbr-mac
      destination: bbr-((version))-darwin
