name: vault
version: 0.11.3
targets:
- platform: linux
  tasks:
  - download:
      url: https://releases.hashicorp.com/vault/0.11.3/vault_0.11.3_linux_amd64.zip
      out: vault-((version))-linux.zip
  - extract:
      archive: vault-((version))-linux.zip
- platform: darwin
  tasks:
  - download:
      url: https://releases.hashicorp.com/vault/0.11.3/vault_0.11.3_darwin_amd64.zip
      out: vault-((version))-darwin.zip
  - extract:
      archive: vault-((version))-darwin.zip
- platform: windows
  tasks:
  - download:
      url: https://releases.hashicorp.com/vault/0.11.3/vault_0.11.3_windows_amd64.zip
      out: vault-((version))-windows.zip
  - extract:
      archive: vault-((version))-windows.zip
