name: bosh
version: 5.3.1
targets:
- platform: windows
  tasks:
  - download:
      url: https://github.com/cloudfoundry/bosh-cli/releases/download/v((version))/bosh-cli-((version))-windows-amd64.exe
      out: bosh-cli-((version))-windows-amd64.exe
- platform: linux
  tasks:
  - download:
      url: https://github.com/cloudfoundry/bosh-cli/releases/download/v((version))/bosh-cli-((version))-linux-amd64
      out: bosh-cli-((version))-linux-amd64
- platform: darwin
  tasks:
  - download:
      url: https://github.com/cloudfoundry/bosh-cli/releases/download/v((version))/bosh-cli-((version))-darwin-amd64
      out: bosh-cli-((version))-darwin-amd64
