name: credhub
version: 1.7.6  
targets:    
- platform: linux
  tasks:
  - download:
      url: https://github.com/cloudfoundry-incubator/credhub-cli/releases/download/((version))/credhub-linux-((version)).tgz      
      out: credhub-linux-((version)).tgz
  - extract:
      archive: credhub-linux-((version)).tgz
- platform: darwin    
  tasks:
  - download:
      url: https://github.com/cloudfoundry-incubator/credhub-cli/releases/download/((version))/credhub-darwin-((version)).tgz      
      out: credhub-darwin-((version)).tgz
  - extract:
      archive: credhub-darwin-((version)).tgz
- platform: windows
  tasks:
  - download:
      url: https://github.com/cloudfoundry-incubator/credhub-cli/releases/download/((version))/credhub-windows-((version)).tgz      
      out: credhub-windows-((version)).tgz
  - extract:
      archive: credhub-windows-((version)).tgz
